

export const CHANGE_TO_BLACK = "CHANGE_TO_BLACK";
export const CHANGE_TO_RED = "CHANGE_TO_RED";
export const CHANGE_TO_COLOR = "CHANGE_TO_COLOR";
export  const CHANGE_TO_COLOR_KNOPKA = "CHANGE_TO_COLOR_KNOPKA";